#!/usr/bin/env bash
# run_tests.sh — StragglAR test suite for a 2-node, 4-GPU cluster.
#
# Topology (fixed):
#   compute1  GPU 0, GPU 1  (RTX 2080 Ti) — MPI ranks 0, 1
#   compute4  GPU 0, GPU 1  (GTX 1070)    — MPI ranks 2, 3
#
# Phase 1 — Straggler detection (N_TRIALS GEMM trials):
#   Launches mpi_smoketest.py across 4 ranks via mpirun.  Each rank times
#   the same GEMM on its local GPU.  An NCCL barrier synchronises the start;
#   rank 0 collects all four timings via all_gather and reports which rank
#   finished last and by how much (delta_ms).
#
# Phase 2 — Significance analysis:
#   Chi-squared and binomial tests on the 1000 straggler identifications.
#   Also extracts the five delta-ms quantiles (min / p25 / median / p75 / max)
#   that drive the Phase 3 benchmark.
#
# Phase 3 — AllReduce speedup benchmark:
#   At each of the five delay points, benchmarks:
#     • Ring AllReduce (ring_allreduce_baseline.py via mpirun)
#     • StragglAR binary (4gpu via mpirun)
#   Reports speedup = ring_mean / sar_mean at every point.
#
# Phase 4 — Final report written to summary.txt.
# Phase 5 — Plots generated by plot_results.py.
#
# Usage:
#   ./run_tests.sh
#
# Configuration (override via env):
#   N_TRIALS          smoketest iterations                 (default: 1000)
#   ITERS_PER_TRIAL   GEMM iters per smoketest trial      (default: 5)
#   ALLREDUCE_ITERS   timed AllReduce iters per benchmark  (default: 20)
#   BUFFER_BYTES      AllReduce buffer size in bytes       (default: 50331648)
#   NCCL_IFNAME       network interface for NCCL           (default: enp5s0)
#   SMOKETEST_PORT    NCCL rendezvous port for Phase 1     (default: 12345)
#   RING_PORT         NCCL rendezvous port for Phase 3     (default: 12346)
#   PY                path to python3 binary               (default: conda env)
#   BINARY            path to StragglAR binary             (auto-detected)
#   RESULTS_DIR       where to save outputs                (default: results/<ts>)

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
N_TRIALS="${N_TRIALS:-1000}"
ITERS_PER_TRIAL="${ITERS_PER_TRIAL:-5}"
ALLREDUCE_ITERS="${ALLREDUCE_ITERS:-20}"
BUFFER_BYTES="${BUFFER_BYTES:-50331648}"     # 48 MiB
NCCL_IFNAME="${NCCL_IFNAME:-enp5s0}"
SMOKETEST_PORT="${SMOKETEST_PORT:-12345}"
RING_PORT="${RING_PORT:-12346}"
SAR_PORT="${SAR_PORT:-12347}"
N_GPUS=4   # fixed: 2 nodes × 2 GPUs each

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
HOSTFILE="$SCRIPT_DIR/hostfile"
MPI_SMOKETEST="$SCRIPT_DIR/mpi_smoketest.py"
RING_SCRIPT="$SCRIPT_DIR/ring_allreduce_baseline.py"
SAR_SCRIPT="$SCRIPT_DIR/stragglar_allreduce.py"
PLOT_SCRIPT="$SCRIPT_DIR/plot_results.py"

TIMESTAMP="$(date +%Y-%m-%d_%H-%M-%S)"
RESULTS_DIR="${RESULTS_DIR:-$SCRIPT_DIR/results/$TIMESTAMP}"

# Python: prefer the conda env present on both nodes; fall back to PATH
PY="${PY:-/home/cadmin/.conda/envs/compilar_env/bin/python3}"
[ ! -x "$PY" ] && PY="$(command -v python3 || true)"
[ -z "$PY" ]   && { echo "Error: python3 not found. Set PY=/path/to/python3" >&2; exit 1; }

MPI="$(command -v mpirun || true)"
[ -z "$MPI" ] && { echo "Error: mpirun not in PATH" >&2; exit 1; }

# Validate required files
for f in "$HOSTFILE" "$MPI_SMOKETEST" "$RING_SCRIPT" "$SAR_SCRIPT"; do
    [ ! -f "$f" ] && { echo "Error: required file not found: $f" >&2; exit 1; }
done

# Prepend PyTorch's bundled NCCL/CUDA libs so both Python workers and the
# binary can find them on every node.
TORCH_LIB="$("$PY" -c 'import torch,os; print(os.path.join(os.path.dirname(torch.__file__),"lib"))' 2>/dev/null || true)"
[ -n "$TORCH_LIB" ] && export LD_LIBRARY_PATH="$TORCH_LIB${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

mkdir -p "$RESULTS_DIR"

SMOKETEST_RESULTS="$RESULTS_DIR/straggler_trials.csv"
SPEEDUP_RESULTS="$RESULTS_DIR/speedup_results.csv"
SIGNIFICANCE_JSON="$RESULTS_DIR/significance.json"
SUMMARY_TXT="$RESULTS_DIR/summary.txt"

NODES="$(grep -v '^[[:space:]]*$' "$HOSTFILE" | awk '{print $1}' | tr '\n' ' ')"

echo "========================================================"
echo " StragglAR Test Suite  (multi-node)"
echo "========================================================"
echo " Nodes            : $NODES"
echo " Ranks            : $N_GPUS  (2 per node)"
echo " Significance runs: $N_TRIALS  (${ITERS_PER_TRIAL} GEMM iters each)"
echo " AllReduce iters  : $ALLREDUCE_ITERS  per benchmark point"
echo " Buffer           : $BUFFER_BYTES bytes  ($((BUFFER_BYTES/1024/1024)) MiB)"
echo " NCCL interface   : $NCCL_IFNAME"
echo " Results dir      : $RESULTS_DIR"
echo "========================================================"
echo ""

# ===========================================================================
# PHASE 1 — Straggler detection across all 4 GPUs
# ===========================================================================
echo "--- Phase 1: Straggler detection  ($N_TRIALS trials) ---"
echo ""

echo "trial,straggler_gpu,delta_ms" > "$SMOKETEST_RESULTS"

START="$(date +%s)"

"$MPI" -n "$N_GPUS" --hostfile "$HOSTFILE" \
    -x MASTER_ADDR=compute1 \
    -x MASTER_PORT="$SMOKETEST_PORT" \
    -x NCCL_SOCKET_IFNAME="$NCCL_IFNAME" \
    -x N_TRIALS="$N_TRIALS" \
    -x ITERS_PER_TRIAL="$ITERS_PER_TRIAL" \
    -x LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-}" \
    "$PY" "$MPI_SMOKETEST" \
| awk -F"STRAGGLER_REPORT=" 'NF>1 {
    split($2, a, ":")
    print a[1]+1 "," a[2] "," a[3]
}' >> "$SMOKETEST_RESULTS"

ELAPSED=$(( $(date +%s) - START ))
echo "Phase 1 complete in ${ELAPSED}s.  Saved: $SMOKETEST_RESULTS"
echo ""

# ===========================================================================
# PHASE 2 — Significance analysis + extract delta quantiles
# ===========================================================================
echo "--- Phase 2: Significance analysis ---"
echo ""

QUANTILES="$("$PY" - "$SMOKETEST_RESULTS" "$N_GPUS" "$N_TRIALS" "$SIGNIFICANCE_JSON" << 'PYEOF'
import sys, csv, math, statistics, json

results_file     = sys.argv[1]
n_gpus           = int(sys.argv[2])
n_trials         = int(sys.argv[3])
significance_out = sys.argv[4]

counts         = {i: 0 for i in range(n_gpus)}
deltas         = []
per_gpu_deltas = {i: [] for i in range(n_gpus)}

with open(results_file) as f:
    for row in csv.DictReader(f):
        g = int(row["straggler_gpu"])
        d = float(row["delta_ms"])
        counts[g] += 1
        deltas.append(d)
        per_gpu_deltas[g].append(d)

total    = sum(counts.values())
p_chance = 1.0 / n_gpus
top_gpu  = max(counts, key=counts.__getitem__)
top_count = counts[top_gpu]

print(f"========================================================", file=sys.stderr)
print(f" Detection Counts  (n={total})", file=sys.stderr)
print(f"========================================================", file=sys.stderr)
print(f" {'Rank':>5}  {'Detections':>12}  {'Rate':>8}  {'Avg delta(ms)':>14}", file=sys.stderr)
print(f" {'-'*5}  {'-'*12}  {'-'*8}  {'-'*14}", file=sys.stderr)
for g in range(n_gpus):
    avg_d = statistics.mean(per_gpu_deltas[g]) if per_gpu_deltas[g] else 0.0
    print(f" {g:>5}  {counts[g]:>12}  {counts[g]/total:>8.1%}  {avg_d:>14.2f}", file=sys.stderr)
print(file=sys.stderr)

expected = total / n_gpus
chi2     = sum((counts[g] - expected) ** 2 / expected for g in range(n_gpus))
df       = n_gpus - 1
CV_TABLE = {1: 3.841, 2: 5.991, 3: 7.815, 4: 9.488}
critical = CV_TABLE.get(df, 7.815)

p_hat        = top_count / total
z            = (p_hat - p_chance) / math.sqrt(p_chance * (1 - p_chance) / total)
p_binom_approx = 0.5 * math.erfc(z / math.sqrt(2))

try:
    from scipy.stats import chisquare, binomtest
    _, chi2_p = chisquare([counts[g] for g in range(n_gpus)], [expected] * n_gpus)
    p_binom   = binomtest(top_count, total, p_chance, alternative="greater").pvalue
    exact     = True
except ImportError:
    chi2_p  = None
    p_binom = p_binom_approx
    exact   = False

chi2_sig  = (chi2_p < 0.05) if chi2_p is not None else (chi2 > critical)
binom_sig = p_binom < 0.05

print(f" Chi-squared  chi2={chi2:.3f}  (critical df={df}: {critical})", file=sys.stderr)
if exact:
    print(f"              p={chi2_p:.4e}  {'SIGNIFICANT' if chi2_sig else 'NOT SIGNIFICANT'}", file=sys.stderr)
else:
    print(f"              {'chi2 > critical → SIGNIFICANT' if chi2_sig else 'NOT SIGNIFICANT'}  (install scipy for exact p)", file=sys.stderr)

print(f" Binomial     rank {top_gpu}: {top_count}/{total} ({p_hat:.1%})", file=sys.stderr)
if exact:
    print(f"              p={p_binom:.4e}  {'SIGNIFICANT' if binom_sig else 'NOT SIGNIFICANT'}", file=sys.stderr)
else:
    print(f"              z={z:.3f}  p≈{p_binom:.4e}  {'SIGNIFICANT' if binom_sig else 'NOT SIGNIFICANT'}", file=sys.stderr)
print(file=sys.stderr)

deltas_sorted = sorted(deltas)

def quantile(s, q):
    idx = q * (len(s) - 1)
    lo, hi = int(idx), min(int(idx) + 1, len(s) - 1)
    return s[lo] + (idx - lo) * (s[hi] - s[lo])

q_stats = {
    "min":  deltas_sorted[0],
    "p25":  quantile(deltas_sorted, 0.25),
    "p50":  quantile(deltas_sorted, 0.50),
    "p75":  quantile(deltas_sorted, 0.75),
    "max":  deltas_sorted[-1],
    "mean": statistics.mean(deltas_sorted),
    "std":  statistics.stdev(deltas_sorted) if len(deltas_sorted) > 1 else 0.0,
}

sig_data = {
    "n_trials":             total,
    "n_gpus":               n_gpus,
    "counts":               {str(g): counts[g] for g in range(n_gpus)},
    "per_gpu_avg_delta":    {str(g): round(statistics.mean(per_gpu_deltas[g]), 3)
                             if per_gpu_deltas[g] else 0.0 for g in range(n_gpus)},
    "top_gpu":              top_gpu,
    "chi2":                 round(chi2, 4),
    "chi2_p":               float(round(chi2_p, 6)) if chi2_p is not None else None,
    "chi2_significant":     bool(chi2_sig),
    "binomial_p":           float(round(p_binom, 6)),
    "binomial_significant": bool(binom_sig),
    "exact_pvalues":        exact,
    "delta_stats":          {k: round(v, 3) for k, v in q_stats.items()},
}
with open(significance_out, "w") as f:
    json.dump(sig_data, f, indent=2)

for k, v in q_stats.items():
    print(f"{k}={v:.3f}")
PYEOF
)"

get_q() { echo "$QUANTILES" | grep "^$1=" | cut -d= -f2; }
D_MIN="$(get_q min)";  D_P25="$(get_q p25)";  D_P50="$(get_q p50)"
D_P75="$(get_q p75)";  D_MAX="$(get_q max)";  D_MEAN="$(get_q mean)"

echo "Straggler delta statistics from $N_TRIALS real trials:"
printf "  min=%.1f ms  p25=%.1f ms  median=%.1f ms  p75=%.1f ms  max=%.1f ms  mean=%.1f ms\n" \
    "$D_MIN" "$D_P25" "$D_P50" "$D_P75" "$D_MAX" "$D_MEAN"
echo "Saved: $SIGNIFICANCE_JSON"
echo ""

# ===========================================================================
# PHASE 3 — AllReduce speedup benchmark
# ===========================================================================
echo "--- Phase 3: AllReduce speedup benchmark ---"
echo ""
echo "  Using real straggler delays from Phase 1."
echo "  Benchmarking ring_allreduce vs StragglAR at: min / p25 / median / p75 / max"
echo ""

echo "label,sleep_ms,ring_ms,sar_ms,speedup" > "$SPEEDUP_RESULTS"

run_bench_point() {
    local label="$1"
    local sleep_ms="$2"

    printf "  %-10s  (sleep=%.1f ms)  ring..." "$label" "$sleep_ms"

    # Ring AllReduce baseline — rank 3 sleeps sleep_ms before all_reduce
    RING_CSV="$(
        "$MPI" -n "$N_GPUS" --hostfile "$HOSTFILE" \
            -x MASTER_ADDR=compute1 \
            -x MASTER_PORT="$RING_PORT" \
            -x NCCL_SOCKET_IFNAME="$NCCL_IFNAME" \
            -x LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-}" \
            "$PY" "$RING_SCRIPT" "$BUFFER_BYTES" "$ALLREDUCE_ITERS" "$sleep_ms" \
            2>/dev/null
    )"
    RING_MEAN="$(echo "$RING_CSV" | awk -F, 'NR>1 && $1=="ring" {sum+=$5; n++} END {printf "%.3f", sum/n}')"

    printf "  done.  sar..."

    # StragglAR — ranks 0-2 overlap with rank 3's sleep using a sub-group AllReduce
    SAR_STDERR="$(mktemp)"
    SAR_CSV="$(
        "$MPI" -n "$N_GPUS" --hostfile "$HOSTFILE" \
            -x MASTER_ADDR=compute1 \
            -x MASTER_PORT="$SAR_PORT" \
            -x NCCL_SOCKET_IFNAME="$NCCL_IFNAME" \
            -x LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-}" \
            "$PY" "$SAR_SCRIPT" "$BUFFER_BYTES" "$ALLREDUCE_ITERS" "$sleep_ms" \
            2>"$SAR_STDERR"
    )" || true

    SAR_DATA_LINES="$(echo "$SAR_CSV" | grep -c '^stragglar,' || true)"
    if [ "${SAR_DATA_LINES:-0}" -eq 0 ]; then
        printf "\n  ERROR: stragglar_allreduce.py produced no data for label=%s sleep_ms=%s\n" \
            "$label" "$sleep_ms" >&2
        printf "  SAR stderr output:\n" >&2
        cat "$SAR_STDERR" >&2
        rm -f "$SAR_STDERR"
        echo "$label,$sleep_ms,$RING_MEAN,ERROR,ERROR" >> "$SPEEDUP_RESULTS"
        echo "  (skipping this benchmark point)"
        return 0
    fi
    rm -f "$SAR_STDERR"

    # Median across all ranks per iteration, then average across iterations
    SAR_MEAN="$(echo "$SAR_CSV" | awk -F, '
        NR>1 && $1=="stragglar" {
            iter=$3; times[iter] = times[iter] "," $5; n[iter]++
        }
        END {
            total=0; count=0
            for (it in times) {
                split(times[it], arr, ",")
                asort(arr)
                mid = int(length(arr)/2)+1
                total += arr[mid]; count++
            }
            if (count > 0) printf "%.3f", total/count
            else print "0"
        }
    ')"

    if [ -z "$SAR_MEAN" ] || [ "$SAR_MEAN" = "0" ]; then
        printf "\n  ERROR: SAR_MEAN is empty or zero for label=%s\n" "$label" >&2
        echo "$label,$sleep_ms,$RING_MEAN,0,ERROR" >> "$SPEEDUP_RESULTS"
        echo "  (skipping speedup calculation)"
        return 0
    fi

    SPEEDUP="$(awk "BEGIN { printf \"%.4f\", $RING_MEAN / $SAR_MEAN }")"

    printf "  done.  ring=%.1f ms  sar=%.1f ms  speedup=%sx\n" \
        "$RING_MEAN" "$SAR_MEAN" "$SPEEDUP"

    echo "$label,$sleep_ms,$RING_MEAN,$SAR_MEAN,$SPEEDUP" >> "$SPEEDUP_RESULTS"
}

run_bench_point "min"    "$D_MIN"
run_bench_point "p25"    "$D_P25"
run_bench_point "median" "$D_P50"
run_bench_point "p75"    "$D_P75"
run_bench_point "max"    "$D_MAX"

echo ""
echo "Saved: $SPEEDUP_RESULTS"
echo ""

# ===========================================================================
# PHASE 4 — Final combined report
# ===========================================================================
"$PY" - "$SMOKETEST_RESULTS" "$SPEEDUP_RESULTS" "$SIGNIFICANCE_JSON" \
        "$N_GPUS" "$N_TRIALS" "$SUMMARY_TXT" << 'PYEOF4'
import sys, csv, json, statistics

smoketest_csv   = sys.argv[1]
speedup_csv     = sys.argv[2]
sig_json        = sys.argv[3]
n_gpus          = int(sys.argv[4])
n_trials        = int(sys.argv[5])
summary_out     = sys.argv[6]

with open(sig_json) as f:
    sig = json.load(f)

speedup_rows = []
with open(speedup_csv) as f:
    for row in csv.DictReader(f):
        speedup_rows.append(row)

speedups = [float(r["speedup"]) for r in speedup_rows]
avg_sp   = statistics.mean(speedups)
best_row = max(speedup_rows, key=lambda r: float(r["speedup"]))
best_sp  = float(best_row["speedup"])

lines = []
lines.append("========================================================")
lines.append(" FINAL REPORT")
lines.append("========================================================")
lines.append(f" Trials run          : {n_trials}")
lines.append(f" Most-detected rank  : rank {sig['top_gpu']}  "
             f"({sig['counts'][str(sig['top_gpu'])]/n_trials:.1%} of trials)")
chi_label = "SIGNIFICANT" if sig["chi2_significant"] else "not significant"
bi_label  = "SIGNIFICANT" if sig["binomial_significant"] else "not significant"
lines.append(f" Chi-squared test    : {chi_label}  "
             f"(chi2={sig['chi2']:.3f}"
             + (f", p={sig['chi2_p']:.2e}" if sig["chi2_p"] is not None else "") + ")")
lines.append(f" Binomial test       : {bi_label}  "
             f"(p={sig['binomial_p']:.2e})")
lines.append("")
lines.append(f" {'Point':<10}  {'Sleep(ms)':>10}  {'Ring(ms)':>10}  {'SAR(ms)':>10}  {'Speedup':>9}")
lines.append(f" {'-'*10}  {'-'*10}  {'-'*10}  {'-'*10}  {'-'*9}")
for r in speedup_rows:
    lines.append(f" {r['label']:<10}  {float(r['sleep_ms']):>10.1f}  "
                 f"{float(r['ring_ms']):>10.3f}  {float(r['sar_ms']):>10.3f}  "
                 f"{float(r['speedup']):>8.4f}x")
lines.append("")
lines.append(f" Average speedup : {avg_sp:.4f}x  (across all 5 delay points)")
lines.append(f" Best run        : {best_sp:.4f}x  "
             f"(at {best_row['label']} delay = {float(best_row['sleep_ms']):.1f} ms)")
lines.append("========================================================")

report = "\n".join(lines)
print(report)
with open(summary_out, "w") as f:
    f.write(report + "\n")
PYEOF4

echo ""
echo "Saved: $SUMMARY_TXT"
echo ""

# ===========================================================================
# PHASE 5 — Generate plots
# ===========================================================================
if [ -f "$PLOT_SCRIPT" ]; then
    echo "--- Phase 5: Generating plots ---"
    echo ""
    "$PY" "$PLOT_SCRIPT" "$RESULTS_DIR" && \
        echo "Plots saved to: $RESULTS_DIR/plots/" || \
        echo "WARNING: plot generation failed  (pip install matplotlib numpy)"
    echo ""
fi

echo "========================================================"
echo " All outputs saved to: $RESULTS_DIR"
echo "   straggler_trials.csv  — raw trial data        (Phase 1)"
echo "   significance.json     — statistical results   (Phase 2)"
echo "   speedup_results.csv   — AllReduce benchmark   (Phase 3)"
echo "   summary.txt           — human-readable report (Phase 4)"
echo "   plots/                — graphs                (Phase 5)"
echo "========================================================"
