// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Source schedule synthesizer: /Users/aryadatla/Documents/compilAR/stragglar/synthesizer_pow2.py
// World size: 16
// Number of rounds: 18

void stragglar_allreduce_generated_16(float** d_buffers, float** d_tempbufs, int* devs, cudaStream_t* streams, ncclComm_t* comms, int numRanks, size_t chunkSize) {
  if (numRanks != 16) {
    printf("Expected numRanks=16, got %d\n", numRanks);
    return;
  }

  // Compile-time offset model from the design doc:
  //   ptr = base + (chunk_id * chunkSize)
  int numBlocks = (chunkSize + RED_ADD_THREADS - 1) / RED_ADD_THREADS;

  // Round 0
  ncclGroupStart();
  ncclSend(d_buffers[0], chunkSize, ncclFloat, 15, comms[0], streams[0]);
  ncclRecv(d_tempbufs[0], chunkSize, ncclFloat, 15, comms[0], streams[0]);
  ncclSend(d_buffers[15], chunkSize, ncclFloat, 0, comms[15], streams[15]);
  ncclRecv(d_tempbufs[15], chunkSize, ncclFloat, 0, comms[15], streams[15]);
  ncclGroupEnd();
  cudaSetDevice(devs[0]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[0]>>>(d_buffers[0], d_tempbufs[0], chunkSize);
  cudaSetDevice(devs[15]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[15]>>>(d_buffers[15], d_tempbufs[15], chunkSize);

  // Round 1
  ncclGroupStart();
  ncclSend(d_buffers[0], chunkSize, ncclFloat, 4, comms[0], streams[0]);
  ncclSend(d_buffers[1] + (1 * chunkSize), chunkSize, ncclFloat, 15, comms[1], streams[1]);
  ncclRecv(d_tempbufs[1], chunkSize, ncclFloat, 15, comms[1], streams[1]);
  ncclRecv(d_buffers[4], chunkSize, ncclFloat, 0, comms[4], streams[4]);
  ncclSend(d_buffers[15] + (1 * chunkSize), chunkSize, ncclFloat, 1, comms[15], streams[15]);
  ncclRecv(d_tempbufs[15], chunkSize, ncclFloat, 1, comms[15], streams[15]);
  ncclGroupEnd();
  cudaSetDevice(devs[1]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[1]>>>(d_buffers[1] + (1 * chunkSize), d_tempbufs[1], chunkSize);
  cudaSetDevice(devs[15]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[15]>>>(d_buffers[15] + (1 * chunkSize), d_tempbufs[15], chunkSize);

  // Round 2
  ncclGroupStart();
  ncclSend(d_buffers[0], chunkSize, ncclFloat, 7, comms[0], streams[0]);
  ncclSend(d_buffers[1] + (1 * chunkSize), chunkSize, ncclFloat, 5, comms[1], streams[1]);
  ncclSend(d_buffers[2] + (2 * chunkSize), chunkSize, ncclFloat, 15, comms[2], streams[2]);
  ncclRecv(d_tempbufs[2], chunkSize, ncclFloat, 15, comms[2], streams[2]);
  ncclSend(d_buffers[4], chunkSize, ncclFloat, 8, comms[4], streams[4]);
  ncclRecv(d_buffers[5] + (1 * chunkSize), chunkSize, ncclFloat, 1, comms[5], streams[5]);
  ncclRecv(d_buffers[7], chunkSize, ncclFloat, 0, comms[7], streams[7]);
  ncclRecv(d_buffers[8], chunkSize, ncclFloat, 4, comms[8], streams[8]);
  ncclSend(d_buffers[15] + (2 * chunkSize), chunkSize, ncclFloat, 2, comms[15], streams[15]);
  ncclRecv(d_tempbufs[15], chunkSize, ncclFloat, 2, comms[15], streams[15]);
  ncclGroupEnd();
  cudaSetDevice(devs[2]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[2]>>>(d_buffers[2] + (2 * chunkSize), d_tempbufs[2], chunkSize);
  cudaSetDevice(devs[15]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[15]>>>(d_buffers[15] + (2 * chunkSize), d_tempbufs[15], chunkSize);

  // Round 3
  ncclGroupStart();
  ncclSend(d_buffers[0], chunkSize, ncclFloat, 9, comms[0], streams[0]);
  ncclSend(d_buffers[1] + (1 * chunkSize), chunkSize, ncclFloat, 10, comms[1], streams[1]);
  ncclSend(d_buffers[2] + (2 * chunkSize), chunkSize, ncclFloat, 6, comms[2], streams[2]);
  ncclSend(d_buffers[3] + (3 * chunkSize), chunkSize, ncclFloat, 15, comms[3], streams[3]);
  ncclRecv(d_tempbufs[3], chunkSize, ncclFloat, 15, comms[3], streams[3]);
  ncclSend(d_buffers[4], chunkSize, ncclFloat, 11, comms[4], streams[4]);
  ncclSend(d_buffers[5] + (1 * chunkSize), chunkSize, ncclFloat, 12, comms[5], streams[5]);
  ncclRecv(d_buffers[6] + (2 * chunkSize), chunkSize, ncclFloat, 2, comms[6], streams[6]);
  ncclSend(d_buffers[7], chunkSize, ncclFloat, 13, comms[7], streams[7]);
  ncclSend(d_buffers[8], chunkSize, ncclFloat, 14, comms[8], streams[8]);
  ncclRecv(d_buffers[9], chunkSize, ncclFloat, 0, comms[9], streams[9]);
  ncclRecv(d_buffers[10] + (1 * chunkSize), chunkSize, ncclFloat, 1, comms[10], streams[10]);
  ncclRecv(d_buffers[11], chunkSize, ncclFloat, 4, comms[11], streams[11]);
  ncclRecv(d_buffers[12] + (1 * chunkSize), chunkSize, ncclFloat, 5, comms[12], streams[12]);
  ncclRecv(d_buffers[13], chunkSize, ncclFloat, 7, comms[13], streams[13]);
  ncclRecv(d_buffers[14], chunkSize, ncclFloat, 8, comms[14], streams[14]);
  ncclSend(d_buffers[15] + (3 * chunkSize), chunkSize, ncclFloat, 3, comms[15], streams[15]);
  ncclRecv(d_tempbufs[15], chunkSize, ncclFloat, 3, comms[15], streams[15]);
  ncclGroupEnd();
  cudaSetDevice(devs[3]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[3]>>>(d_buffers[3] + (3 * chunkSize), d_tempbufs[3], chunkSize);
  cudaSetDevice(devs[15]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[15]>>>(d_buffers[15] + (3 * chunkSize), d_tempbufs[15], chunkSize);

  // Round 4
  ncclGroupStart();
  ncclSend(d_buffers[0], chunkSize, ncclFloat, 5, comms[0], streams[0]);
  ncclRecv(d_buffers[0] + (1 * chunkSize), chunkSize, ncclFloat, 5, comms[0], streams[0]);
  ncclSend(d_buffers[1] + (1 * chunkSize), chunkSize, ncclFloat, 7, comms[1], streams[1]);
  ncclRecv(d_buffers[1], chunkSize, ncclFloat, 7, comms[1], streams[1]);
  ncclSend(d_buffers[2] + (2 * chunkSize), chunkSize, ncclFloat, 13, comms[2], streams[2]);
  ncclRecv(d_buffers[2], chunkSize, ncclFloat, 13, comms[2], streams[2]);
  ncclSend(d_buffers[3] + (3 * chunkSize), chunkSize, ncclFloat, 14, comms[3], streams[3]);
  ncclRecv(d_buffers[3], chunkSize, ncclFloat, 14, comms[3], streams[3]);
  ncclSend(d_buffers[4] + (4 * chunkSize), chunkSize, ncclFloat, 15, comms[4], streams[4]);
  ncclRecv(d_tempbufs[4], chunkSize, ncclFloat, 15, comms[4], streams[4]);
  ncclSend(d_buffers[5] + (1 * chunkSize), chunkSize, ncclFloat, 0, comms[5], streams[5]);
  ncclRecv(d_buffers[5], chunkSize, ncclFloat, 0, comms[5], streams[5]);
  ncclSend(d_buffers[6] + (2 * chunkSize), chunkSize, ncclFloat, 8, comms[6], streams[6]);
  ncclRecv(d_buffers[6], chunkSize, ncclFloat, 8, comms[6], streams[6]);
  ncclSend(d_buffers[7], chunkSize, ncclFloat, 1, comms[7], streams[7]);
  ncclRecv(d_buffers[7] + (1 * chunkSize), chunkSize, ncclFloat, 1, comms[7], streams[7]);
  ncclSend(d_buffers[8], chunkSize, ncclFloat, 6, comms[8], streams[8]);
  ncclRecv(d_buffers[8] + (2 * chunkSize), chunkSize, ncclFloat, 6, comms[8], streams[8]);
  ncclSend(d_buffers[9], chunkSize, ncclFloat, 10, comms[9], streams[9]);
  ncclRecv(d_buffers[9] + (1 * chunkSize), chunkSize, ncclFloat, 10, comms[9], streams[9]);
  ncclSend(d_buffers[10] + (1 * chunkSize), chunkSize, ncclFloat, 9, comms[10], streams[10]);
  ncclRecv(d_buffers[10], chunkSize, ncclFloat, 9, comms[10], streams[10]);
  ncclSend(d_buffers[11], chunkSize, ncclFloat, 12, comms[11], streams[11]);
  ncclRecv(d_buffers[11] + (1 * chunkSize), chunkSize, ncclFloat, 12, comms[11], streams[11]);
  ncclSend(d_buffers[12] + (1 * chunkSize), chunkSize, ncclFloat, 11, comms[12], streams[12]);
  ncclRecv(d_buffers[12], chunkSize, ncclFloat, 11, comms[12], streams[12]);
  ncclSend(d_buffers[13], chunkSize, ncclFloat, 2, comms[13], streams[13]);
  ncclRecv(d_buffers[13] + (2 * chunkSize), chunkSize, ncclFloat, 2, comms[13], streams[13]);
  ncclSend(d_buffers[14], chunkSize, ncclFloat, 3, comms[14], streams[14]);
  ncclRecv(d_buffers[14] + (3 * chunkSize), chunkSize, ncclFloat, 3, comms[14], streams[14]);
  ncclSend(d_buffers[15] + (4 * chunkSize), chunkSize, ncclFloat, 4, comms[15], streams[15]);
  ncclRecv(d_tempbufs[15], chunkSize, ncclFloat, 4, comms[15], streams[15]);
  ncclGroupEnd();
  cudaSetDevice(devs[4]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[4]>>>(d_buffers[4] + (4 * chunkSize), d_tempbufs[4], chunkSize);
  cudaSetDevice(devs[15]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[15]>>>(d_buffers[15] + (4 * chunkSize), d_tempbufs[15], chunkSize);

  // Round 5
  ncclGroupStart();
  ncclSend(d_buffers[0] + (1 * chunkSize), chunkSize, ncclFloat, 6, comms[0], streams[0]);
  ncclRecv(d_buffers[0] + (2 * chunkSize), chunkSize, ncclFloat, 6, comms[0], streams[0]);
  ncclSend(d_buffers[1] + (1 * chunkSize), chunkSize, ncclFloat, 8, comms[1], streams[1]);
  ncclRecv(d_buffers[1] + (2 * chunkSize), chunkSize, ncclFloat, 8, comms[1], streams[1]);
  ncclSend(d_buffers[2] + (2 * chunkSize), chunkSize, ncclFloat, 7, comms[2], streams[2]);
  ncclRecv(d_buffers[2] + (1 * chunkSize), chunkSize, ncclFloat, 7, comms[2], streams[2]);
  ncclSend(d_buffers[3] + (3 * chunkSize), chunkSize, ncclFloat, 10, comms[3], streams[3]);
  ncclRecv(d_buffers[3] + (1 * chunkSize), chunkSize, ncclFloat, 10, comms[3], streams[3]);
  ncclSend(d_buffers[4] + (4 * chunkSize), chunkSize, ncclFloat, 12, comms[4], streams[4]);
  ncclRecv(d_buffers[4] + (1 * chunkSize), chunkSize, ncclFloat, 12, comms[4], streams[4]);
  ncclSend(d_buffers[5] + (5 * chunkSize), chunkSize, ncclFloat, 15, comms[5], streams[5]);
  ncclRecv(d_tempbufs[5], chunkSize, ncclFloat, 15, comms[5], streams[5]);
  ncclSend(d_buffers[6] + (2 * chunkSize), chunkSize, ncclFloat, 0, comms[6], streams[6]);
  ncclRecv(d_buffers[6] + (1 * chunkSize), chunkSize, ncclFloat, 0, comms[6], streams[6]);
  ncclSend(d_buffers[7] + (1 * chunkSize), chunkSize, ncclFloat, 2, comms[7], streams[7]);
  ncclRecv(d_buffers[7] + (2 * chunkSize), chunkSize, ncclFloat, 2, comms[7], streams[7]);
  ncclSend(d_buffers[8] + (2 * chunkSize), chunkSize, ncclFloat, 1, comms[8], streams[8]);
  ncclRecv(d_buffers[8] + (1 * chunkSize), chunkSize, ncclFloat, 1, comms[8], streams[8]);
  ncclSend(d_buffers[9] + (1 * chunkSize), chunkSize, ncclFloat, 13, comms[9], streams[9]);
  ncclRecv(d_buffers[9] + (2 * chunkSize), chunkSize, ncclFloat, 13, comms[9], streams[9]);
  ncclSend(d_buffers[10] + (1 * chunkSize), chunkSize, ncclFloat, 3, comms[10], streams[10]);
  ncclRecv(d_buffers[10] + (3 * chunkSize), chunkSize, ncclFloat, 3, comms[10], streams[10]);
  ncclSend(d_buffers[11] + (1 * chunkSize), chunkSize, ncclFloat, 14, comms[11], streams[11]);
  ncclRecv(d_buffers[11] + (3 * chunkSize), chunkSize, ncclFloat, 14, comms[11], streams[11]);
  ncclSend(d_buffers[12] + (1 * chunkSize), chunkSize, ncclFloat, 4, comms[12], streams[12]);
  ncclRecv(d_buffers[12] + (4 * chunkSize), chunkSize, ncclFloat, 4, comms[12], streams[12]);
  ncclSend(d_buffers[13] + (2 * chunkSize), chunkSize, ncclFloat, 9, comms[13], streams[13]);
  ncclRecv(d_buffers[13] + (1 * chunkSize), chunkSize, ncclFloat, 9, comms[13], streams[13]);
  ncclSend(d_buffers[14] + (3 * chunkSize), chunkSize, ncclFloat, 11, comms[14], streams[14]);
  ncclRecv(d_buffers[14] + (1 * chunkSize), chunkSize, ncclFloat, 11, comms[14], streams[14]);
  ncclSend(d_buffers[15] + (5 * chunkSize), chunkSize, ncclFloat, 5, comms[15], streams[15]);
  ncclRecv(d_tempbufs[15], chunkSize, ncclFloat, 5, comms[15], streams[15]);
  ncclGroupEnd();
  cudaSetDevice(devs[5]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[5]>>>(d_buffers[5] + (5 * chunkSize), d_tempbufs[5], chunkSize);
  cudaSetDevice(devs[15]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[15]>>>(d_buffers[15] + (5 * chunkSize), d_tempbufs[15], chunkSize);

  // Round 6
  ncclGroupStart();
  ncclSend(d_buffers[0] + (2 * chunkSize), chunkSize, ncclFloat, 14, comms[0], streams[0]);
  ncclRecv(d_buffers[0] + (3 * chunkSize), chunkSize, ncclFloat, 14, comms[0], streams[0]);
  ncclSend(d_buffers[1] + (2 * chunkSize), chunkSize, ncclFloat, 4, comms[1], streams[1]);
  ncclRecv(d_buffers[1] + (4 * chunkSize), chunkSize, ncclFloat, 4, comms[1], streams[1]);
  ncclSend(d_buffers[2] + (2 * chunkSize), chunkSize, ncclFloat, 12, comms[2], streams[2]);
  ncclRecv(d_buffers[2] + (4 * chunkSize), chunkSize, ncclFloat, 12, comms[2], streams[2]);
  ncclSend(d_buffers[3] + (3 * chunkSize), chunkSize, ncclFloat, 7, comms[3], streams[3]);
  ncclRecv(d_buffers[3] + (2 * chunkSize), chunkSize, ncclFloat, 7, comms[3], streams[3]);
  ncclSend(d_buffers[4] + (4 * chunkSize), chunkSize, ncclFloat, 1, comms[4], streams[4]);
  ncclRecv(d_buffers[4] + (2 * chunkSize), chunkSize, ncclFloat, 1, comms[4], streams[4]);
  ncclSend(d_buffers[5] + (5 * chunkSize), chunkSize, ncclFloat, 13, comms[5], streams[5]);
  ncclRecv(d_buffers[5] + (2 * chunkSize), chunkSize, ncclFloat, 13, comms[5], streams[5]);
  ncclSend(d_buffers[6] + (6 * chunkSize), chunkSize, ncclFloat, 15, comms[6], streams[6]);
  ncclRecv(d_tempbufs[6], chunkSize, ncclFloat, 15, comms[6], streams[6]);
  ncclSend(d_buffers[7] + (2 * chunkSize), chunkSize, ncclFloat, 3, comms[7], streams[7]);
  ncclRecv(d_buffers[7] + (3 * chunkSize), chunkSize, ncclFloat, 3, comms[7], streams[7]);
  ncclSend(d_buffers[8] + (2 * chunkSize), chunkSize, ncclFloat, 10, comms[8], streams[8]);
  ncclRecv(d_buffers[8] + (3 * chunkSize), chunkSize, ncclFloat, 10, comms[8], streams[8]);
  ncclSend(d_buffers[9] + (2 * chunkSize), chunkSize, ncclFloat, 11, comms[9], streams[9]);
  ncclRecv(d_buffers[9] + (3 * chunkSize), chunkSize, ncclFloat, 11, comms[9], streams[9]);
  ncclSend(d_buffers[10] + (3 * chunkSize), chunkSize, ncclFloat, 8, comms[10], streams[10]);
  ncclRecv(d_buffers[10] + (2 * chunkSize), chunkSize, ncclFloat, 8, comms[10], streams[10]);
  ncclSend(d_buffers[11] + (3 * chunkSize), chunkSize, ncclFloat, 9, comms[11], streams[11]);
  ncclRecv(d_buffers[11] + (2 * chunkSize), chunkSize, ncclFloat, 9, comms[11], streams[11]);
  ncclSend(d_buffers[12] + (4 * chunkSize), chunkSize, ncclFloat, 2, comms[12], streams[12]);
  ncclRecv(d_buffers[12] + (2 * chunkSize), chunkSize, ncclFloat, 2, comms[12], streams[12]);
  ncclSend(d_buffers[13] + (2 * chunkSize), chunkSize, ncclFloat, 5, comms[13], streams[13]);
  ncclRecv(d_buffers[13] + (5 * chunkSize), chunkSize, ncclFloat, 5, comms[13], streams[13]);
  ncclSend(d_buffers[14] + (3 * chunkSize), chunkSize, ncclFloat, 0, comms[14], streams[14]);
  ncclRecv(d_buffers[14] + (2 * chunkSize), chunkSize, ncclFloat, 0, comms[14], streams[14]);
  ncclSend(d_buffers[15] + (6 * chunkSize), chunkSize, ncclFloat, 6, comms[15], streams[15]);
  ncclRecv(d_tempbufs[15], chunkSize, ncclFloat, 6, comms[15], streams[15]);
  ncclGroupEnd();
  cudaSetDevice(devs[6]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[6]>>>(d_buffers[6] + (6 * chunkSize), d_tempbufs[6], chunkSize);
  cudaSetDevice(devs[15]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[15]>>>(d_buffers[15] + (6 * chunkSize), d_tempbufs[15], chunkSize);

  // Round 7
  ncclGroupStart();
  ncclSend(d_buffers[0] + (3 * chunkSize), chunkSize, ncclFloat, 12, comms[0], streams[0]);
  ncclRecv(d_buffers[0] + (4 * chunkSize), chunkSize, ncclFloat, 12, comms[0], streams[0]);
  ncclSend(d_buffers[1] + (4 * chunkSize), chunkSize, ncclFloat, 8, comms[1], streams[1]);
  ncclRecv(d_buffers[1] + (3 * chunkSize), chunkSize, ncclFloat, 8, comms[1], streams[1]);
  ncclSend(d_buffers[2] + (4 * chunkSize), chunkSize, ncclFloat, 9, comms[2], streams[2]);
  ncclRecv(d_buffers[2] + (3 * chunkSize), chunkSize, ncclFloat, 9, comms[2], streams[2]);
  ncclSend(d_buffers[3] + (3 * chunkSize), chunkSize, ncclFloat, 5, comms[3], streams[3]);
  ncclRecv(d_buffers[3] + (5 * chunkSize), chunkSize, ncclFloat, 5, comms[3], streams[3]);
  ncclSend(d_buffers[4] + (4 * chunkSize), chunkSize, ncclFloat, 10, comms[4], streams[4]);
  ncclRecv(d_buffers[4] + (3 * chunkSize), chunkSize, ncclFloat, 10, comms[4], streams[4]);
  ncclSend(d_buffers[5] + (5 * chunkSize), chunkSize, ncclFloat, 3, comms[5], streams[5]);
  ncclRecv(d_buffers[5] + (3 * chunkSize), chunkSize, ncclFloat, 3, comms[5], streams[5]);
  ncclSend(d_buffers[6] + (6 * chunkSize), chunkSize, ncclFloat, 14, comms[6], streams[6]);
  ncclRecv(d_buffers[6] + (3 * chunkSize), chunkSize, ncclFloat, 14, comms[6], streams[6]);
  ncclSend(d_buffers[7] + (7 * chunkSize), chunkSize, ncclFloat, 15, comms[7], streams[7]);
  ncclRecv(d_tempbufs[7], chunkSize, ncclFloat, 15, comms[7], streams[7]);
  ncclSend(d_buffers[8] + (3 * chunkSize), chunkSize, ncclFloat, 1, comms[8], streams[8]);
  ncclRecv(d_buffers[8] + (4 * chunkSize), chunkSize, ncclFloat, 1, comms[8], streams[8]);
  ncclSend(d_buffers[9] + (3 * chunkSize), chunkSize, ncclFloat, 2, comms[9], streams[9]);
  ncclRecv(d_buffers[9] + (4 * chunkSize), chunkSize, ncclFloat, 2, comms[9], streams[9]);
  ncclSend(d_buffers[10] + (3 * chunkSize), chunkSize, ncclFloat, 4, comms[10], streams[10]);
  ncclRecv(d_buffers[10] + (4 * chunkSize), chunkSize, ncclFloat, 4, comms[10], streams[10]);
  ncclSend(d_buffers[11] + (3 * chunkSize), chunkSize, ncclFloat, 13, comms[11], streams[11]);
  ncclRecv(d_buffers[11] + (5 * chunkSize), chunkSize, ncclFloat, 13, comms[11], streams[11]);
  ncclSend(d_buffers[12] + (4 * chunkSize), chunkSize, ncclFloat, 0, comms[12], streams[12]);
  ncclRecv(d_buffers[12] + (3 * chunkSize), chunkSize, ncclFloat, 0, comms[12], streams[12]);
  ncclSend(d_buffers[13] + (5 * chunkSize), chunkSize, ncclFloat, 11, comms[13], streams[13]);
  ncclRecv(d_buffers[13] + (3 * chunkSize), chunkSize, ncclFloat, 11, comms[13], streams[13]);
  ncclSend(d_buffers[14] + (3 * chunkSize), chunkSize, ncclFloat, 6, comms[14], streams[14]);
  ncclRecv(d_buffers[14] + (6 * chunkSize), chunkSize, ncclFloat, 6, comms[14], streams[14]);
  ncclSend(d_buffers[15] + (7 * chunkSize), chunkSize, ncclFloat, 7, comms[15], streams[15]);
  ncclRecv(d_tempbufs[15], chunkSize, ncclFloat, 7, comms[15], streams[15]);
  ncclGroupEnd();
  cudaSetDevice(devs[7]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[7]>>>(d_buffers[7] + (7 * chunkSize), d_tempbufs[7], chunkSize);
  cudaSetDevice(devs[15]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[15]>>>(d_buffers[15] + (7 * chunkSize), d_tempbufs[15], chunkSize);

  // Round 8
  ncclGroupStart();
  ncclSend(d_buffers[0] + (4 * chunkSize), chunkSize, ncclFloat, 11, comms[0], streams[0]);
  ncclRecv(d_buffers[0] + (5 * chunkSize), chunkSize, ncclFloat, 11, comms[0], streams[0]);
  ncclSend(d_buffers[1] + (4 * chunkSize), chunkSize, ncclFloat, 13, comms[1], streams[1]);
  ncclRecv(d_buffers[1] + (5 * chunkSize), chunkSize, ncclFloat, 13, comms[1], streams[1]);
  ncclSend(d_buffers[2] + (4 * chunkSize), chunkSize, ncclFloat, 6, comms[2], streams[2]);
  ncclRecv(d_buffers[2] + (6 * chunkSize), chunkSize, ncclFloat, 6, comms[2], streams[2]);
  ncclSend(d_buffers[3] + (5 * chunkSize), chunkSize, ncclFloat, 9, comms[3], streams[3]);
  ncclRecv(d_buffers[3] + (4 * chunkSize), chunkSize, ncclFloat, 9, comms[3], streams[3]);
  ncclSend(d_buffers[4] + (4 * chunkSize), chunkSize, ncclFloat, 14, comms[4], streams[4]);
  ncclRecv(d_buffers[4] + (6 * chunkSize), chunkSize, ncclFloat, 14, comms[4], streams[4]);
  ncclSend(d_buffers[5] + (5 * chunkSize), chunkSize, ncclFloat, 10, comms[5], streams[5]);
  ncclRecv(d_buffers[5] + (4 * chunkSize), chunkSize, ncclFloat, 10, comms[5], streams[5]);
  ncclSend(d_buffers[6] + (6 * chunkSize), chunkSize, ncclFloat, 2, comms[6], streams[6]);
  ncclRecv(d_buffers[6] + (4 * chunkSize), chunkSize, ncclFloat, 2, comms[6], streams[6]);
  ncclSend(d_buffers[7] + (7 * chunkSize), chunkSize, ncclFloat, 12, comms[7], streams[7]);
  ncclRecv(d_buffers[7] + (4 * chunkSize), chunkSize, ncclFloat, 12, comms[7], streams[7]);
  ncclSend(d_buffers[8] + (8 * chunkSize), chunkSize, ncclFloat, 15, comms[8], streams[8]);
  ncclRecv(d_tempbufs[8], chunkSize, ncclFloat, 15, comms[8], streams[8]);
  ncclSend(d_buffers[9] + (4 * chunkSize), chunkSize, ncclFloat, 3, comms[9], streams[9]);
  ncclRecv(d_buffers[9] + (5 * chunkSize), chunkSize, ncclFloat, 3, comms[9], streams[9]);
  ncclSend(d_buffers[10] + (4 * chunkSize), chunkSize, ncclFloat, 5, comms[10], streams[10]);
  ncclRecv(d_buffers[10] + (5 * chunkSize), chunkSize, ncclFloat, 5, comms[10], streams[10]);
  ncclSend(d_buffers[11] + (5 * chunkSize), chunkSize, ncclFloat, 0, comms[11], streams[11]);
  ncclRecv(d_buffers[11] + (4 * chunkSize), chunkSize, ncclFloat, 0, comms[11], streams[11]);
  ncclSend(d_buffers[12] + (4 * chunkSize), chunkSize, ncclFloat, 7, comms[12], streams[12]);
  ncclRecv(d_buffers[12] + (7 * chunkSize), chunkSize, ncclFloat, 7, comms[12], streams[12]);
  ncclSend(d_buffers[13] + (5 * chunkSize), chunkSize, ncclFloat, 1, comms[13], streams[13]);
  ncclRecv(d_buffers[13] + (4 * chunkSize), chunkSize, ncclFloat, 1, comms[13], streams[13]);
  ncclSend(d_buffers[14] + (6 * chunkSize), chunkSize, ncclFloat, 4, comms[14], streams[14]);
  ncclRecv(d_buffers[14] + (4 * chunkSize), chunkSize, ncclFloat, 4, comms[14], streams[14]);
  ncclSend(d_buffers[15] + (8 * chunkSize), chunkSize, ncclFloat, 8, comms[15], streams[15]);
  ncclRecv(d_tempbufs[15], chunkSize, ncclFloat, 8, comms[15], streams[15]);
  ncclGroupEnd();
  cudaSetDevice(devs[8]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[8]>>>(d_buffers[8] + (8 * chunkSize), d_tempbufs[8], chunkSize);
  cudaSetDevice(devs[15]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[15]>>>(d_buffers[15] + (8 * chunkSize), d_tempbufs[15], chunkSize);

  // Round 9
  ncclGroupStart();
  ncclSend(d_buffers[0] + (5 * chunkSize), chunkSize, ncclFloat, 12, comms[0], streams[0]);
  ncclRecv(d_buffers[0] + (7 * chunkSize), chunkSize, ncclFloat, 12, comms[0], streams[0]);
  ncclSend(d_buffers[1] + (5 * chunkSize), chunkSize, ncclFloat, 6, comms[1], streams[1]);
  ncclRecv(d_buffers[1] + (6 * chunkSize), chunkSize, ncclFloat, 6, comms[1], streams[1]);
  ncclSend(d_buffers[2] + (6 * chunkSize), chunkSize, ncclFloat, 10, comms[2], streams[2]);
  ncclRecv(d_buffers[2] + (5 * chunkSize), chunkSize, ncclFloat, 10, comms[2], streams[2]);
  ncclSend(d_buffers[3] + (5 * chunkSize), chunkSize, ncclFloat, 14, comms[3], streams[3]);
  ncclRecv(d_buffers[3] + (6 * chunkSize), chunkSize, ncclFloat, 14, comms[3], streams[3]);
  ncclSend(d_buffers[4] + (6 * chunkSize), chunkSize, ncclFloat, 11, comms[4], streams[4]);
  ncclRecv(d_buffers[4] + (5 * chunkSize), chunkSize, ncclFloat, 11, comms[4], streams[4]);
  ncclSend(d_buffers[5] + (5 * chunkSize), chunkSize, ncclFloat, 7, comms[5], streams[5]);
  ncclRecv(d_buffers[5] + (7 * chunkSize), chunkSize, ncclFloat, 7, comms[5], streams[5]);
  ncclSend(d_buffers[6] + (6 * chunkSize), chunkSize, ncclFloat, 1, comms[6], streams[6]);
  ncclRecv(d_buffers[6] + (5 * chunkSize), chunkSize, ncclFloat, 1, comms[6], streams[6]);
  ncclSend(d_buffers[7] + (7 * chunkSize), chunkSize, ncclFloat, 5, comms[7], streams[7]);
  ncclRecv(d_buffers[7] + (5 * chunkSize), chunkSize, ncclFloat, 5, comms[7], streams[7]);
  ncclSend(d_buffers[8] + (8 * chunkSize), chunkSize, ncclFloat, 13, comms[8], streams[8]);
  ncclRecv(d_buffers[8] + (5 * chunkSize), chunkSize, ncclFloat, 13, comms[8], streams[8]);
  ncclSend(d_buffers[9] + (9 * chunkSize), chunkSize, ncclFloat, 15, comms[9], streams[9]);
  ncclRecv(d_tempbufs[9], chunkSize, ncclFloat, 15, comms[9], streams[9]);
  ncclSend(d_buffers[10] + (5 * chunkSize), chunkSize, ncclFloat, 2, comms[10], streams[10]);
  ncclRecv(d_buffers[10] + (6 * chunkSize), chunkSize, ncclFloat, 2, comms[10], streams[10]);
  ncclSend(d_buffers[11] + (5 * chunkSize), chunkSize, ncclFloat, 4, comms[11], streams[11]);
  ncclRecv(d_buffers[11] + (6 * chunkSize), chunkSize, ncclFloat, 4, comms[11], streams[11]);
  ncclSend(d_buffers[12] + (7 * chunkSize), chunkSize, ncclFloat, 0, comms[12], streams[12]);
  ncclRecv(d_buffers[12] + (5 * chunkSize), chunkSize, ncclFloat, 0, comms[12], streams[12]);
  ncclSend(d_buffers[13] + (5 * chunkSize), chunkSize, ncclFloat, 8, comms[13], streams[13]);
  ncclRecv(d_buffers[13] + (8 * chunkSize), chunkSize, ncclFloat, 8, comms[13], streams[13]);
  ncclSend(d_buffers[14] + (6 * chunkSize), chunkSize, ncclFloat, 3, comms[14], streams[14]);
  ncclRecv(d_buffers[14] + (5 * chunkSize), chunkSize, ncclFloat, 3, comms[14], streams[14]);
  ncclSend(d_buffers[15] + (9 * chunkSize), chunkSize, ncclFloat, 9, comms[15], streams[15]);
  ncclRecv(d_tempbufs[15], chunkSize, ncclFloat, 9, comms[15], streams[15]);
  ncclGroupEnd();
  cudaSetDevice(devs[9]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[9]>>>(d_buffers[9] + (9 * chunkSize), d_tempbufs[9], chunkSize);
  cudaSetDevice(devs[15]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[15]>>>(d_buffers[15] + (9 * chunkSize), d_tempbufs[15], chunkSize);

  // Round 10
  ncclGroupStart();
  ncclSend(d_buffers[0] + (7 * chunkSize), chunkSize, ncclFloat, 11, comms[0], streams[0]);
  ncclRecv(d_buffers[0] + (6 * chunkSize), chunkSize, ncclFloat, 11, comms[0], streams[0]);
  ncclSend(d_buffers[1] + (6 * chunkSize), chunkSize, ncclFloat, 12, comms[1], streams[1]);
  ncclRecv(d_buffers[1] + (7 * chunkSize), chunkSize, ncclFloat, 12, comms[1], streams[1]);
  ncclSend(d_buffers[2] + (6 * chunkSize), chunkSize, ncclFloat, 13, comms[2], streams[2]);
  ncclRecv(d_buffers[2] + (8 * chunkSize), chunkSize, ncclFloat, 13, comms[2], streams[2]);
  ncclSend(d_buffers[3] + (6 * chunkSize), chunkSize, ncclFloat, 5, comms[3], streams[3]);
  ncclRecv(d_buffers[3] + (7 * chunkSize), chunkSize, ncclFloat, 5, comms[3], streams[3]);
  ncclSend(d_buffers[4] + (6 * chunkSize), chunkSize, ncclFloat, 7, comms[4], streams[4]);
  ncclRecv(d_buffers[4] + (7 * chunkSize), chunkSize, ncclFloat, 7, comms[4], streams[4]);
  ncclSend(d_buffers[5] + (7 * chunkSize), chunkSize, ncclFloat, 3, comms[5], streams[5]);
  ncclRecv(d_buffers[5] + (6 * chunkSize), chunkSize, ncclFloat, 3, comms[5], streams[5]);
  ncclSend(d_buffers[6] + (6 * chunkSize), chunkSize, ncclFloat, 8, comms[6], streams[6]);
  ncclRecv(d_buffers[6] + (8 * chunkSize), chunkSize, ncclFloat, 8, comms[6], streams[6]);
  ncclSend(d_buffers[7] + (7 * chunkSize), chunkSize, ncclFloat, 4, comms[7], streams[7]);
  ncclRecv(d_buffers[7] + (6 * chunkSize), chunkSize, ncclFloat, 4, comms[7], streams[7]);
  ncclSend(d_buffers[8] + (8 * chunkSize), chunkSize, ncclFloat, 6, comms[8], streams[8]);
  ncclRecv(d_buffers[8] + (6 * chunkSize), chunkSize, ncclFloat, 6, comms[8], streams[8]);
  ncclSend(d_buffers[9] + (9 * chunkSize), chunkSize, ncclFloat, 14, comms[9], streams[9]);
  ncclRecv(d_buffers[9] + (6 * chunkSize), chunkSize, ncclFloat, 14, comms[9], streams[9]);
  ncclSend(d_buffers[10] + (10 * chunkSize), chunkSize, ncclFloat, 15, comms[10], streams[10]);
  ncclRecv(d_tempbufs[10], chunkSize, ncclFloat, 15, comms[10], streams[10]);
  ncclSend(d_buffers[11] + (6 * chunkSize), chunkSize, ncclFloat, 0, comms[11], streams[11]);
  ncclRecv(d_buffers[11] + (7 * chunkSize), chunkSize, ncclFloat, 0, comms[11], streams[11]);
  ncclSend(d_buffers[12] + (7 * chunkSize), chunkSize, ncclFloat, 1, comms[12], streams[12]);
  ncclRecv(d_buffers[12] + (6 * chunkSize), chunkSize, ncclFloat, 1, comms[12], streams[12]);
  ncclSend(d_buffers[13] + (8 * chunkSize), chunkSize, ncclFloat, 2, comms[13], streams[13]);
  ncclRecv(d_buffers[13] + (6 * chunkSize), chunkSize, ncclFloat, 2, comms[13], streams[13]);
  ncclSend(d_buffers[14] + (6 * chunkSize), chunkSize, ncclFloat, 9, comms[14], streams[14]);
  ncclRecv(d_buffers[14] + (9 * chunkSize), chunkSize, ncclFloat, 9, comms[14], streams[14]);
  ncclSend(d_buffers[15] + (10 * chunkSize), chunkSize, ncclFloat, 10, comms[15], streams[15]);
  ncclRecv(d_tempbufs[15], chunkSize, ncclFloat, 10, comms[15], streams[15]);
  ncclGroupEnd();
  cudaSetDevice(devs[10]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[10]>>>(d_buffers[10] + (10 * chunkSize), d_tempbufs[10], chunkSize);
  cudaSetDevice(devs[15]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[15]>>>(d_buffers[15] + (10 * chunkSize), d_tempbufs[15], chunkSize);

  // Round 11
  ncclGroupStart();
  ncclSend(d_buffers[0] + (7 * chunkSize), chunkSize, ncclFloat, 13, comms[0], streams[0]);
  ncclRecv(d_buffers[0] + (8 * chunkSize), chunkSize, ncclFloat, 13, comms[0], streams[0]);
  ncclSend(d_buffers[1] + (7 * chunkSize), chunkSize, ncclFloat, 14, comms[1], streams[1]);
  ncclRecv(d_buffers[1] + (9 * chunkSize), chunkSize, ncclFloat, 14, comms[1], streams[1]);
  ncclSend(d_buffers[2] + (8 * chunkSize), chunkSize, ncclFloat, 12, comms[2], streams[2]);
  ncclRecv(d_buffers[2] + (7 * chunkSize), chunkSize, ncclFloat, 12, comms[2], streams[2]);
  ncclSend(d_buffers[3] + (7 * chunkSize), chunkSize, ncclFloat, 6, comms[3], streams[3]);
  ncclRecv(d_buffers[3] + (8 * chunkSize), chunkSize, ncclFloat, 6, comms[3], streams[3]);
  ncclSend(d_buffers[4] + (7 * chunkSize), chunkSize, ncclFloat, 8, comms[4], streams[4]);
  ncclRecv(d_buffers[4] + (8 * chunkSize), chunkSize, ncclFloat, 8, comms[4], streams[4]);
  ncclSend(d_buffers[5] + (7 * chunkSize), chunkSize, ncclFloat, 9, comms[5], streams[5]);
  ncclRecv(d_buffers[5] + (9 * chunkSize), chunkSize, ncclFloat, 9, comms[5], streams[5]);
  ncclSend(d_buffers[6] + (8 * chunkSize), chunkSize, ncclFloat, 3, comms[6], streams[6]);
  ncclRecv(d_buffers[6] + (7 * chunkSize), chunkSize, ncclFloat, 3, comms[6], streams[6]);
  ncclSend(d_buffers[7] + (7 * chunkSize), chunkSize, ncclFloat, 10, comms[7], streams[7]);
  ncclRecv(d_buffers[7] + (10 * chunkSize), chunkSize, ncclFloat, 10, comms[7], streams[7]);
  ncclSend(d_buffers[8] + (8 * chunkSize), chunkSize, ncclFloat, 4, comms[8], streams[8]);
  ncclRecv(d_buffers[8] + (7 * chunkSize), chunkSize, ncclFloat, 4, comms[8], streams[8]);
  ncclSend(d_buffers[9] + (9 * chunkSize), chunkSize, ncclFloat, 5, comms[9], streams[9]);
  ncclRecv(d_buffers[9] + (7 * chunkSize), chunkSize, ncclFloat, 5, comms[9], streams[9]);
  ncclSend(d_buffers[10] + (10 * chunkSize), chunkSize, ncclFloat, 7, comms[10], streams[10]);
  ncclRecv(d_buffers[10] + (7 * chunkSize), chunkSize, ncclFloat, 7, comms[10], streams[10]);
  ncclSend(d_buffers[11] + (11 * chunkSize), chunkSize, ncclFloat, 15, comms[11], streams[11]);
  ncclRecv(d_tempbufs[11], chunkSize, ncclFloat, 15, comms[11], streams[11]);
  ncclSend(d_buffers[12] + (7 * chunkSize), chunkSize, ncclFloat, 2, comms[12], streams[12]);
  ncclRecv(d_buffers[12] + (8 * chunkSize), chunkSize, ncclFloat, 2, comms[12], streams[12]);
  ncclSend(d_buffers[13] + (8 * chunkSize), chunkSize, ncclFloat, 0, comms[13], streams[13]);
  ncclRecv(d_buffers[13] + (7 * chunkSize), chunkSize, ncclFloat, 0, comms[13], streams[13]);
  ncclSend(d_buffers[14] + (9 * chunkSize), chunkSize, ncclFloat, 1, comms[14], streams[14]);
  ncclRecv(d_buffers[14] + (7 * chunkSize), chunkSize, ncclFloat, 1, comms[14], streams[14]);
  ncclSend(d_buffers[15] + (11 * chunkSize), chunkSize, ncclFloat, 11, comms[15], streams[15]);
  ncclRecv(d_tempbufs[15], chunkSize, ncclFloat, 11, comms[15], streams[15]);
  ncclGroupEnd();
  cudaSetDevice(devs[11]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[11]>>>(d_buffers[11] + (11 * chunkSize), d_tempbufs[11], chunkSize);
  cudaSetDevice(devs[15]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[15]>>>(d_buffers[15] + (11 * chunkSize), d_tempbufs[15], chunkSize);

  // Round 12
  ncclGroupStart();
  ncclSend(d_buffers[0] + (8 * chunkSize), chunkSize, ncclFloat, 14, comms[0], streams[0]);
  ncclRecv(d_buffers[0] + (9 * chunkSize), chunkSize, ncclFloat, 14, comms[0], streams[0]);
  ncclSend(d_buffers[1] + (9 * chunkSize), chunkSize, ncclFloat, 13, comms[1], streams[1]);
  ncclRecv(d_buffers[1] + (8 * chunkSize), chunkSize, ncclFloat, 13, comms[1], streams[1]);
  ncclSend(d_buffers[2] + (8 * chunkSize), chunkSize, ncclFloat, 5, comms[2], streams[2]);
  ncclRecv(d_buffers[2] + (9 * chunkSize), chunkSize, ncclFloat, 5, comms[2], streams[2]);
  ncclSend(d_buffers[3] + (8 * chunkSize), chunkSize, ncclFloat, 9, comms[3], streams[3]);
  ncclRecv(d_buffers[3] + (9 * chunkSize), chunkSize, ncclFloat, 9, comms[3], streams[3]);
  ncclSend(d_buffers[4] + (8 * chunkSize), chunkSize, ncclFloat, 7, comms[4], streams[4]);
  ncclRecv(d_buffers[4] + (10 * chunkSize), chunkSize, ncclFloat, 7, comms[4], streams[4]);
  ncclSend(d_buffers[5] + (9 * chunkSize), chunkSize, ncclFloat, 2, comms[5], streams[5]);
  ncclRecv(d_buffers[5] + (8 * chunkSize), chunkSize, ncclFloat, 2, comms[5], streams[5]);
  ncclSend(d_buffers[6] + (8 * chunkSize), chunkSize, ncclFloat, 10, comms[6], streams[6]);
  ncclRecv(d_buffers[6] + (10 * chunkSize), chunkSize, ncclFloat, 10, comms[6], streams[6]);
  ncclSend(d_buffers[7] + (10 * chunkSize), chunkSize, ncclFloat, 4, comms[7], streams[7]);
  ncclRecv(d_buffers[7] + (8 * chunkSize), chunkSize, ncclFloat, 4, comms[7], streams[7]);
  ncclSend(d_buffers[8] + (8 * chunkSize), chunkSize, ncclFloat, 11, comms[8], streams[8]);
  ncclRecv(d_buffers[8] + (11 * chunkSize), chunkSize, ncclFloat, 11, comms[8], streams[8]);
  ncclSend(d_buffers[9] + (9 * chunkSize), chunkSize, ncclFloat, 3, comms[9], streams[9]);
  ncclRecv(d_buffers[9] + (8 * chunkSize), chunkSize, ncclFloat, 3, comms[9], streams[9]);
  ncclSend(d_buffers[10] + (10 * chunkSize), chunkSize, ncclFloat, 6, comms[10], streams[10]);
  ncclRecv(d_buffers[10] + (8 * chunkSize), chunkSize, ncclFloat, 6, comms[10], streams[10]);
  ncclSend(d_buffers[11] + (11 * chunkSize), chunkSize, ncclFloat, 8, comms[11], streams[11]);
  ncclRecv(d_buffers[11] + (8 * chunkSize), chunkSize, ncclFloat, 8, comms[11], streams[11]);
  ncclSend(d_buffers[12] + (12 * chunkSize), chunkSize, ncclFloat, 15, comms[12], streams[12]);
  ncclRecv(d_tempbufs[12], chunkSize, ncclFloat, 15, comms[12], streams[12]);
  ncclSend(d_buffers[13] + (8 * chunkSize), chunkSize, ncclFloat, 1, comms[13], streams[13]);
  ncclRecv(d_buffers[13] + (9 * chunkSize), chunkSize, ncclFloat, 1, comms[13], streams[13]);
  ncclSend(d_buffers[14] + (9 * chunkSize), chunkSize, ncclFloat, 0, comms[14], streams[14]);
  ncclRecv(d_buffers[14] + (8 * chunkSize), chunkSize, ncclFloat, 0, comms[14], streams[14]);
  ncclSend(d_buffers[15] + (12 * chunkSize), chunkSize, ncclFloat, 12, comms[15], streams[15]);
  ncclRecv(d_tempbufs[15], chunkSize, ncclFloat, 12, comms[15], streams[15]);
  ncclGroupEnd();
  cudaSetDevice(devs[12]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[12]>>>(d_buffers[12] + (12 * chunkSize), d_tempbufs[12], chunkSize);
  cudaSetDevice(devs[15]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[15]>>>(d_buffers[15] + (12 * chunkSize), d_tempbufs[15], chunkSize);

  // Round 13
  ncclGroupStart();
  ncclSend(d_buffers[0] + (9 * chunkSize), chunkSize, ncclFloat, 6, comms[0], streams[0]);
  ncclRecv(d_buffers[0] + (10 * chunkSize), chunkSize, ncclFloat, 6, comms[0], streams[0]);
  ncclSend(d_buffers[1] + (9 * chunkSize), chunkSize, ncclFloat, 7, comms[1], streams[1]);
  ncclRecv(d_buffers[1] + (10 * chunkSize), chunkSize, ncclFloat, 7, comms[1], streams[1]);
  ncclSend(d_buffers[2] + (9 * chunkSize), chunkSize, ncclFloat, 10, comms[2], streams[2]);
  ncclRecv(d_buffers[2] + (10 * chunkSize), chunkSize, ncclFloat, 10, comms[2], streams[2]);
  ncclSend(d_buffers[3] + (9 * chunkSize), chunkSize, ncclFloat, 8, comms[3], streams[3]);
  ncclRecv(d_buffers[3] + (11 * chunkSize), chunkSize, ncclFloat, 8, comms[3], streams[3]);
  ncclSend(d_buffers[4] + (10 * chunkSize), chunkSize, ncclFloat, 14, comms[4], streams[4]);
  ncclRecv(d_buffers[4] + (9 * chunkSize), chunkSize, ncclFloat, 14, comms[4], streams[4]);
  ncclSend(d_buffers[5] + (9 * chunkSize), chunkSize, ncclFloat, 11, comms[5], streams[5]);
  ncclRecv(d_buffers[5] + (11 * chunkSize), chunkSize, ncclFloat, 11, comms[5], streams[5]);
  ncclSend(d_buffers[6] + (10 * chunkSize), chunkSize, ncclFloat, 0, comms[6], streams[6]);
  ncclRecv(d_buffers[6] + (9 * chunkSize), chunkSize, ncclFloat, 0, comms[6], streams[6]);
  ncclSend(d_buffers[7] + (10 * chunkSize), chunkSize, ncclFloat, 1, comms[7], streams[7]);
  ncclRecv(d_buffers[7] + (9 * chunkSize), chunkSize, ncclFloat, 1, comms[7], streams[7]);
  ncclSend(d_buffers[8] + (11 * chunkSize), chunkSize, ncclFloat, 3, comms[8], streams[8]);
  ncclRecv(d_buffers[8] + (9 * chunkSize), chunkSize, ncclFloat, 3, comms[8], streams[8]);
  ncclSend(d_buffers[9] + (9 * chunkSize), chunkSize, ncclFloat, 12, comms[9], streams[9]);
  ncclRecv(d_buffers[9] + (12 * chunkSize), chunkSize, ncclFloat, 12, comms[9], streams[9]);
  ncclSend(d_buffers[10] + (10 * chunkSize), chunkSize, ncclFloat, 2, comms[10], streams[10]);
  ncclRecv(d_buffers[10] + (9 * chunkSize), chunkSize, ncclFloat, 2, comms[10], streams[10]);
  ncclSend(d_buffers[11] + (11 * chunkSize), chunkSize, ncclFloat, 5, comms[11], streams[11]);
  ncclRecv(d_buffers[11] + (9 * chunkSize), chunkSize, ncclFloat, 5, comms[11], streams[11]);
  ncclSend(d_buffers[12] + (12 * chunkSize), chunkSize, ncclFloat, 9, comms[12], streams[12]);
  ncclRecv(d_buffers[12] + (9 * chunkSize), chunkSize, ncclFloat, 9, comms[12], streams[12]);
  ncclSend(d_buffers[13] + (13 * chunkSize), chunkSize, ncclFloat, 15, comms[13], streams[13]);
  ncclRecv(d_tempbufs[13], chunkSize, ncclFloat, 15, comms[13], streams[13]);
  ncclSend(d_buffers[14] + (9 * chunkSize), chunkSize, ncclFloat, 4, comms[14], streams[14]);
  ncclRecv(d_buffers[14] + (10 * chunkSize), chunkSize, ncclFloat, 4, comms[14], streams[14]);
  ncclSend(d_buffers[15] + (13 * chunkSize), chunkSize, ncclFloat, 13, comms[15], streams[15]);
  ncclRecv(d_tempbufs[15], chunkSize, ncclFloat, 13, comms[15], streams[15]);
  ncclGroupEnd();
  cudaSetDevice(devs[13]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[13]>>>(d_buffers[13] + (13 * chunkSize), d_tempbufs[13], chunkSize);
  cudaSetDevice(devs[15]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[15]>>>(d_buffers[15] + (13 * chunkSize), d_tempbufs[15], chunkSize);

  // Round 14
  ncclGroupStart();
  ncclSend(d_buffers[0] + (10 * chunkSize), chunkSize, ncclFloat, 3, comms[0], streams[0]);
  ncclRecv(d_buffers[0] + (11 * chunkSize), chunkSize, ncclFloat, 3, comms[0], streams[0]);
  ncclSend(d_buffers[1] + (10 * chunkSize), chunkSize, ncclFloat, 5, comms[1], streams[1]);
  ncclRecv(d_buffers[1] + (11 * chunkSize), chunkSize, ncclFloat, 5, comms[1], streams[1]);
  ncclSend(d_buffers[2] + (10 * chunkSize), chunkSize, ncclFloat, 8, comms[2], streams[2]);
  ncclRecv(d_buffers[2] + (11 * chunkSize), chunkSize, ncclFloat, 8, comms[2], streams[2]);
  ncclSend(d_buffers[3] + (11 * chunkSize), chunkSize, ncclFloat, 0, comms[3], streams[3]);
  ncclRecv(d_buffers[3] + (10 * chunkSize), chunkSize, ncclFloat, 0, comms[3], streams[3]);
  ncclSend(d_buffers[4] + (10 * chunkSize), chunkSize, ncclFloat, 11, comms[4], streams[4]);
  ncclRecv(d_buffers[4] + (11 * chunkSize), chunkSize, ncclFloat, 11, comms[4], streams[4]);
  ncclSend(d_buffers[5] + (11 * chunkSize), chunkSize, ncclFloat, 1, comms[5], streams[5]);
  ncclRecv(d_buffers[5] + (10 * chunkSize), chunkSize, ncclFloat, 1, comms[5], streams[5]);
  ncclSend(d_buffers[6] + (10 * chunkSize), chunkSize, ncclFloat, 9, comms[6], streams[6]);
  ncclRecv(d_buffers[6] + (12 * chunkSize), chunkSize, ncclFloat, 9, comms[6], streams[6]);
  ncclSend(d_buffers[7] + (10 * chunkSize), chunkSize, ncclFloat, 12, comms[7], streams[7]);
  ncclRecv(d_buffers[7] + (12 * chunkSize), chunkSize, ncclFloat, 12, comms[7], streams[7]);
  ncclSend(d_buffers[8] + (11 * chunkSize), chunkSize, ncclFloat, 2, comms[8], streams[8]);
  ncclRecv(d_buffers[8] + (10 * chunkSize), chunkSize, ncclFloat, 2, comms[8], streams[8]);
  ncclSend(d_buffers[9] + (12 * chunkSize), chunkSize, ncclFloat, 6, comms[9], streams[9]);
  ncclRecv(d_buffers[9] + (10 * chunkSize), chunkSize, ncclFloat, 6, comms[9], streams[9]);
  ncclSend(d_buffers[10] + (10 * chunkSize), chunkSize, ncclFloat, 13, comms[10], streams[10]);
  ncclRecv(d_buffers[10] + (13 * chunkSize), chunkSize, ncclFloat, 13, comms[10], streams[10]);
  ncclSend(d_buffers[11] + (11 * chunkSize), chunkSize, ncclFloat, 4, comms[11], streams[11]);
  ncclRecv(d_buffers[11] + (10 * chunkSize), chunkSize, ncclFloat, 4, comms[11], streams[11]);
  ncclSend(d_buffers[12] + (12 * chunkSize), chunkSize, ncclFloat, 7, comms[12], streams[12]);
  ncclRecv(d_buffers[12] + (10 * chunkSize), chunkSize, ncclFloat, 7, comms[12], streams[12]);
  ncclSend(d_buffers[13] + (13 * chunkSize), chunkSize, ncclFloat, 10, comms[13], streams[13]);
  ncclRecv(d_buffers[13] + (10 * chunkSize), chunkSize, ncclFloat, 10, comms[13], streams[13]);
  ncclSend(d_buffers[14] + (14 * chunkSize), chunkSize, ncclFloat, 15, comms[14], streams[14]);
  ncclRecv(d_tempbufs[14], chunkSize, ncclFloat, 15, comms[14], streams[14]);
  ncclSend(d_buffers[15] + (14 * chunkSize), chunkSize, ncclFloat, 14, comms[15], streams[15]);
  ncclRecv(d_tempbufs[15], chunkSize, ncclFloat, 14, comms[15], streams[15]);
  ncclGroupEnd();
  cudaSetDevice(devs[14]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[14]>>>(d_buffers[14] + (14 * chunkSize), d_tempbufs[14], chunkSize);
  cudaSetDevice(devs[15]);
  reduce_add<<<numBlocks, RED_ADD_THREADS, 0, streams[15]>>>(d_buffers[15] + (14 * chunkSize), d_tempbufs[15], chunkSize);

  // Round 15
  ncclGroupStart();
  ncclSend(d_buffers[0] + (11 * chunkSize), chunkSize, ncclFloat, 6, comms[0], streams[0]);
  ncclRecv(d_buffers[0] + (12 * chunkSize), chunkSize, ncclFloat, 6, comms[0], streams[0]);
  ncclSend(d_buffers[1] + (11 * chunkSize), chunkSize, ncclFloat, 7, comms[1], streams[1]);
  ncclRecv(d_buffers[1] + (12 * chunkSize), chunkSize, ncclFloat, 7, comms[1], streams[1]);
  ncclSend(d_buffers[2] + (11 * chunkSize), chunkSize, ncclFloat, 9, comms[2], streams[2]);
  ncclRecv(d_buffers[2] + (12 * chunkSize), chunkSize, ncclFloat, 9, comms[2], streams[2]);
  ncclSend(d_buffers[3] + (11 * chunkSize), chunkSize, ncclFloat, 12, comms[3], streams[3]);
  ncclRecv(d_buffers[3] + (12 * chunkSize), chunkSize, ncclFloat, 12, comms[3], streams[3]);
  ncclSend(d_buffers[4] + (11 * chunkSize), chunkSize, ncclFloat, 10, comms[4], streams[4]);
  ncclRecv(d_buffers[4] + (13 * chunkSize), chunkSize, ncclFloat, 10, comms[4], streams[4]);
  ncclSend(d_buffers[5] + (11 * chunkSize), chunkSize, ncclFloat, 13, comms[5], streams[5]);
  ncclRecv(d_buffers[5] + (13 * chunkSize), chunkSize, ncclFloat, 13, comms[5], streams[5]);
  ncclSend(d_buffers[6] + (12 * chunkSize), chunkSize, ncclFloat, 0, comms[6], streams[6]);
  ncclRecv(d_buffers[6] + (11 * chunkSize), chunkSize, ncclFloat, 0, comms[6], streams[6]);
  ncclSend(d_buffers[7] + (12 * chunkSize), chunkSize, ncclFloat, 1, comms[7], streams[7]);
  ncclRecv(d_buffers[7] + (11 * chunkSize), chunkSize, ncclFloat, 1, comms[7], streams[7]);
  ncclSend(d_buffers[8] + (11 * chunkSize), chunkSize, ncclFloat, 14, comms[8], streams[8]);
  ncclRecv(d_buffers[8] + (14 * chunkSize), chunkSize, ncclFloat, 14, comms[8], streams[8]);
  ncclSend(d_buffers[9] + (12 * chunkSize), chunkSize, ncclFloat, 2, comms[9], streams[9]);
  ncclRecv(d_buffers[9] + (11 * chunkSize), chunkSize, ncclFloat, 2, comms[9], streams[9]);
  ncclSend(d_buffers[10] + (13 * chunkSize), chunkSize, ncclFloat, 4, comms[10], streams[10]);
  ncclRecv(d_buffers[10] + (11 * chunkSize), chunkSize, ncclFloat, 4, comms[10], streams[10]);
  ncclRecv(d_buffers[11] + (14 * chunkSize), chunkSize, ncclFloat, 15, comms[11], streams[11]);
  ncclSend(d_buffers[12] + (12 * chunkSize), chunkSize, ncclFloat, 3, comms[12], streams[12]);
  ncclRecv(d_buffers[12] + (11 * chunkSize), chunkSize, ncclFloat, 3, comms[12], streams[12]);
  ncclSend(d_buffers[13] + (13 * chunkSize), chunkSize, ncclFloat, 5, comms[13], streams[13]);
  ncclRecv(d_buffers[13] + (11 * chunkSize), chunkSize, ncclFloat, 5, comms[13], streams[13]);
  ncclSend(d_buffers[14] + (14 * chunkSize), chunkSize, ncclFloat, 8, comms[14], streams[14]);
  ncclRecv(d_buffers[14] + (11 * chunkSize), chunkSize, ncclFloat, 8, comms[14], streams[14]);
  ncclSend(d_buffers[15] + (14 * chunkSize), chunkSize, ncclFloat, 11, comms[15], streams[15]);
  ncclGroupEnd();

  // Round 16
  ncclGroupStart();
  ncclSend(d_buffers[0] + (12 * chunkSize), chunkSize, ncclFloat, 4, comms[0], streams[0]);
  ncclRecv(d_buffers[0] + (13 * chunkSize), chunkSize, ncclFloat, 4, comms[0], streams[0]);
  ncclSend(d_buffers[1] + (12 * chunkSize), chunkSize, ncclFloat, 5, comms[1], streams[1]);
  ncclRecv(d_buffers[1] + (13 * chunkSize), chunkSize, ncclFloat, 5, comms[1], streams[1]);
  ncclSend(d_buffers[2] + (12 * chunkSize), chunkSize, ncclFloat, 10, comms[2], streams[2]);
  ncclRecv(d_buffers[2] + (13 * chunkSize), chunkSize, ncclFloat, 10, comms[2], streams[2]);
  ncclSend(d_buffers[3] + (12 * chunkSize), chunkSize, ncclFloat, 13, comms[3], streams[3]);
  ncclRecv(d_buffers[3] + (13 * chunkSize), chunkSize, ncclFloat, 13, comms[3], streams[3]);
  ncclSend(d_buffers[4] + (13 * chunkSize), chunkSize, ncclFloat, 0, comms[4], streams[4]);
  ncclRecv(d_buffers[4] + (12 * chunkSize), chunkSize, ncclFloat, 0, comms[4], streams[4]);
  ncclSend(d_buffers[5] + (13 * chunkSize), chunkSize, ncclFloat, 1, comms[5], streams[5]);
  ncclRecv(d_buffers[5] + (12 * chunkSize), chunkSize, ncclFloat, 1, comms[5], streams[5]);
  ncclSend(d_buffers[6] + (12 * chunkSize), chunkSize, ncclFloat, 8, comms[6], streams[6]);
  ncclRecv(d_buffers[6] + (14 * chunkSize), chunkSize, ncclFloat, 8, comms[6], streams[6]);
  ncclSend(d_buffers[7] + (12 * chunkSize), chunkSize, ncclFloat, 11, comms[7], streams[7]);
  ncclRecv(d_buffers[7] + (14 * chunkSize), chunkSize, ncclFloat, 11, comms[7], streams[7]);
  ncclSend(d_buffers[8] + (14 * chunkSize), chunkSize, ncclFloat, 6, comms[8], streams[8]);
  ncclRecv(d_buffers[8] + (12 * chunkSize), chunkSize, ncclFloat, 6, comms[8], streams[8]);
  ncclSend(d_buffers[9] + (12 * chunkSize), chunkSize, ncclFloat, 14, comms[9], streams[9]);
  ncclRecv(d_buffers[9] + (14 * chunkSize), chunkSize, ncclFloat, 14, comms[9], streams[9]);
  ncclSend(d_buffers[10] + (13 * chunkSize), chunkSize, ncclFloat, 2, comms[10], streams[10]);
  ncclRecv(d_buffers[10] + (12 * chunkSize), chunkSize, ncclFloat, 2, comms[10], streams[10]);
  ncclSend(d_buffers[11] + (14 * chunkSize), chunkSize, ncclFloat, 7, comms[11], streams[11]);
  ncclRecv(d_buffers[11] + (12 * chunkSize), chunkSize, ncclFloat, 7, comms[11], streams[11]);
  ncclRecv(d_buffers[12] + (14 * chunkSize), chunkSize, ncclFloat, 15, comms[12], streams[12]);
  ncclSend(d_buffers[13] + (13 * chunkSize), chunkSize, ncclFloat, 3, comms[13], streams[13]);
  ncclRecv(d_buffers[13] + (12 * chunkSize), chunkSize, ncclFloat, 3, comms[13], streams[13]);
  ncclSend(d_buffers[14] + (14 * chunkSize), chunkSize, ncclFloat, 9, comms[14], streams[14]);
  ncclRecv(d_buffers[14] + (12 * chunkSize), chunkSize, ncclFloat, 9, comms[14], streams[14]);
  ncclSend(d_buffers[15] + (14 * chunkSize), chunkSize, ncclFloat, 12, comms[15], streams[15]);
  ncclGroupEnd();

  // Round 17
  ncclGroupStart();
  ncclSend(d_buffers[0] + (13 * chunkSize), chunkSize, ncclFloat, 6, comms[0], streams[0]);
  ncclRecv(d_buffers[0] + (14 * chunkSize), chunkSize, ncclFloat, 6, comms[0], streams[0]);
  ncclSend(d_buffers[1] + (13 * chunkSize), chunkSize, ncclFloat, 7, comms[1], streams[1]);
  ncclRecv(d_buffers[1] + (14 * chunkSize), chunkSize, ncclFloat, 7, comms[1], streams[1]);
  ncclSend(d_buffers[2] + (13 * chunkSize), chunkSize, ncclFloat, 8, comms[2], streams[2]);
  ncclRecv(d_buffers[2] + (14 * chunkSize), chunkSize, ncclFloat, 8, comms[2], streams[2]);
  ncclSend(d_buffers[3] + (13 * chunkSize), chunkSize, ncclFloat, 9, comms[3], streams[3]);
  ncclRecv(d_buffers[3] + (14 * chunkSize), chunkSize, ncclFloat, 9, comms[3], streams[3]);
  ncclSend(d_buffers[4] + (13 * chunkSize), chunkSize, ncclFloat, 11, comms[4], streams[4]);
  ncclRecv(d_buffers[4] + (14 * chunkSize), chunkSize, ncclFloat, 11, comms[4], streams[4]);
  ncclSend(d_buffers[5] + (13 * chunkSize), chunkSize, ncclFloat, 12, comms[5], streams[5]);
  ncclRecv(d_buffers[5] + (14 * chunkSize), chunkSize, ncclFloat, 12, comms[5], streams[5]);
  ncclSend(d_buffers[6] + (14 * chunkSize), chunkSize, ncclFloat, 0, comms[6], streams[6]);
  ncclRecv(d_buffers[6] + (13 * chunkSize), chunkSize, ncclFloat, 0, comms[6], streams[6]);
  ncclSend(d_buffers[7] + (14 * chunkSize), chunkSize, ncclFloat, 1, comms[7], streams[7]);
  ncclRecv(d_buffers[7] + (13 * chunkSize), chunkSize, ncclFloat, 1, comms[7], streams[7]);
  ncclSend(d_buffers[8] + (14 * chunkSize), chunkSize, ncclFloat, 2, comms[8], streams[8]);
  ncclRecv(d_buffers[8] + (13 * chunkSize), chunkSize, ncclFloat, 2, comms[8], streams[8]);
  ncclSend(d_buffers[9] + (14 * chunkSize), chunkSize, ncclFloat, 3, comms[9], streams[9]);
  ncclRecv(d_buffers[9] + (13 * chunkSize), chunkSize, ncclFloat, 3, comms[9], streams[9]);
  ncclSend(d_buffers[10] + (13 * chunkSize), chunkSize, ncclFloat, 14, comms[10], streams[10]);
  ncclRecv(d_buffers[10] + (14 * chunkSize), chunkSize, ncclFloat, 14, comms[10], streams[10]);
  ncclSend(d_buffers[11] + (14 * chunkSize), chunkSize, ncclFloat, 4, comms[11], streams[11]);
  ncclRecv(d_buffers[11] + (13 * chunkSize), chunkSize, ncclFloat, 4, comms[11], streams[11]);
  ncclSend(d_buffers[12] + (14 * chunkSize), chunkSize, ncclFloat, 5, comms[12], streams[12]);
  ncclRecv(d_buffers[12] + (13 * chunkSize), chunkSize, ncclFloat, 5, comms[12], streams[12]);
  ncclRecv(d_buffers[13] + (14 * chunkSize), chunkSize, ncclFloat, 15, comms[13], streams[13]);
  ncclSend(d_buffers[14] + (14 * chunkSize), chunkSize, ncclFloat, 10, comms[14], streams[14]);
  ncclRecv(d_buffers[14] + (13 * chunkSize), chunkSize, ncclFloat, 10, comms[14], streams[14]);
  ncclSend(d_buffers[15] + (14 * chunkSize), chunkSize, ncclFloat, 13, comms[15], streams[15]);
  ncclGroupEnd();

}
